# Generated by Django 3.2.4 on 2022-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='service',
            field=models.CharField(choices=[('Služby', 'Služby'), ('Django', 'Django'), ('Django REST Framework', 'Django REST Framework'), ('Flask', 'Flask'), ('Dátová Analýza', 'Dátová Analýza'), ('Front-end Development', 'Front-end Development'), ('Web Scraping', 'Web Scraping')], default='Služby', max_length=25),
        ),
    ]
